//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileTools.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.9.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Beams_AreRotated {
            get {
                return ((bool)(this["Beams_AreRotated"]));
            }
            set {
                this["Beams_AreRotated"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.5")]
        public double Clip_THK {
            get {
                return ((double)(this["Clip_THK"]));
            }
            set {
                this["Clip_THK"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.375")]
        public double EndPanel_THK {
            get {
                return ((double)(this["EndPanel_THK"]));
            }
            set {
                this["EndPanel_THK"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.375")]
        public double SidePanel_THK {
            get {
                return ((double)(this["SidePanel_THK"]));
            }
            set {
                this["SidePanel_THK"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("W8x31")]
        public string Beam_Size {
            get {
                return ((string)(this["Beam_Size"]));
            }
            set {
                this["Beam_Size"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Standard")]
        public string PlenumDesignSetting {
            get {
                return ((string)(this["PlenumDesignSetting"]));
            }
            set {
                this["PlenumDesignSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("240")]
        public double Plenum_Length {
            get {
                return ((double)(this["Plenum_Length"]));
            }
            set {
                this["Plenum_Length"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("108")]
        public double Plenum_Width {
            get {
                return ((double)(this["Plenum_Width"]));
            }
            set {
                this["Plenum_Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int Fan_Count {
            get {
                return ((int)(this["Fan_Count"]));
            }
            set {
                this["Fan_Count"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("36")]
        public double Plenum_Depth {
            get {
                return ((double)(this["Plenum_Depth"]));
            }
            set {
                this["Plenum_Depth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Mid_Columns {
            get {
                return ((bool)(this["Mid_Columns"]));
            }
            set {
                this["Mid_Columns"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public double Fan_Diameter_Feet {
            get {
                return ((double)(this["Fan_Diameter_Feet"]));
            }
            set {
                this["Fan_Diameter_Feet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("24")]
        public double FanRing_Depth {
            get {
                return ((double)(this["FanRing_Depth"]));
            }
            set {
                this["FanRing_Depth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Motor Shaft Down")]
        public string MotorShaft_Orientation {
            get {
                return ((string)(this["MotorShaft_Orientation"]));
            }
            set {
                this["MotorShaft_Orientation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("A572_50")]
        public string MaterialSpecSetting {
            get {
                return ((string)(this["MaterialSpecSetting"]));
            }
            set {
                this["MaterialSpecSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public double Beam_Depth {
            get {
                return ((double)(this["Beam_Depth"]));
            }
            set {
                this["Beam_Depth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.25")]
        public double Beam_WebTHK {
            get {
                return ((double)(this["Beam_WebTHK"]));
            }
            set {
                this["Beam_WebTHK"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public double Beam_FlangeWidth {
            get {
                return ((double)(this["Beam_FlangeWidth"]));
            }
            set {
                this["Beam_FlangeWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.25")]
        public double Beam_FlangeTHK {
            get {
                return ((double)(this["Beam_FlangeTHK"]));
            }
            set {
                this["Beam_FlangeTHK"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.625")]
        public double Beam_K {
            get {
                return ((double)(this["Beam_K"]));
            }
            set {
                this["Beam_K"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.375")]
        public double Beam_K1 {
            get {
                return ((double)(this["Beam_K1"]));
            }
            set {
                this["Beam_K1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3.5")]
        public double Beam_FlangeGage {
            get {
                return ((double)(this["Beam_FlangeGage"]));
            }
            set {
                this["Beam_FlangeGage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2.25")]
        public double Beam_WebGage {
            get {
                return ((double)(this["Beam_WebGage"]));
            }
            set {
                this["Beam_WebGage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MotorBeam_Required {
            get {
                return ((bool)(this["MotorBeam_Required"]));
            }
            set {
                this["MotorBeam_Required"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("M000")]
        public string Project {
            get {
                return ((string)(this["Project"]));
            }
            set {
                this["Project"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Customer")]
        public string Customer {
            get {
                return ((string)(this["Customer"]));
            }
            set {
                this["Customer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Client")]
        public string Client {
            get {
                return ((string)(this["Client"]));
            }
            set {
                this["Client"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Location")]
        public string PlantLocation {
            get {
                return ((string)(this["PlantLocation"]));
            }
            set {
                this["PlantLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Purchase Order")]
        public string PurchaseOrder {
            get {
                return ((string)(this["PurchaseOrder"]));
            }
            set {
                this["PurchaseOrder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Item Number")]
        public string ItemNumber {
            get {
                return ((string)(this["ItemNumber"]));
            }
            set {
                this["ItemNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Your Initials")]
        public string Initials {
            get {
                return ((string)(this["Initials"]));
            }
            set {
                this["Initials"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("A")]
        public char Bank {
            get {
                return ((char)(this["Bank"]));
            }
            set {
                this["Bank"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Johnson_ExtraLength {
            get {
                return ((double)(this["Johnson_ExtraLength"]));
            }
            set {
                this["Johnson_ExtraLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Toggle_CreateDrawing {
            get {
                return ((bool)(this["Toggle_CreateDrawing"]));
            }
            set {
                this["Toggle_CreateDrawing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Toggle_Save {
            get {
                return ((bool)(this["Toggle_Save"]));
            }
            set {
                this["Toggle_Save"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Toggle_DeleteFiles {
            get {
                return ((bool)(this["Toggle_DeleteFiles"]));
            }
            set {
                this["Toggle_DeleteFiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("120")]
        public double TotalColumnHeight {
            get {
                return ((double)(this["TotalColumnHeight"]));
            }
            set {
                this["TotalColumnHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public double BasePlate_Width {
            get {
                return ((double)(this["BasePlate_Width"]));
            }
            set {
                this["BasePlate_Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public double BasePlate_Length {
            get {
                return ((double)(this["BasePlate_Length"]));
            }
            set {
                this["BasePlate_Length"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4.5")]
        public double BasePlate_WidthHoleSpacing {
            get {
                return ((double)(this["BasePlate_WidthHoleSpacing"]));
            }
            set {
                this["BasePlate_WidthHoleSpacing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4.5")]
        public double BasePlate_LengthHoleSpacing {
            get {
                return ((double)(this["BasePlate_LengthHoleSpacing"]));
            }
            set {
                this["BasePlate_LengthHoleSpacing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.8125")]
        public double BasePlate_HoleDiameter {
            get {
                return ((double)(this["BasePlate_HoleDiameter"]));
            }
            set {
                this["BasePlate_HoleDiameter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("54")]
        public double MachineryMount_Height {
            get {
                return ((double)(this["MachineryMount_Height"]));
            }
            set {
                this["MachineryMount_Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TX")]
        public string BraceType {
            get {
                return ((string)(this["BraceType"]));
            }
            set {
                this["BraceType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.8125")]
        public double HoleDiameter_Structural {
            get {
                return ((double)(this["HoleDiameter_Structural"]));
            }
            set {
                this["HoleDiameter_Structural"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public double BraceAngle {
            get {
                return ((double)(this["BraceAngle"]));
            }
            set {
                this["BraceAngle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public double AngleBrace_Leg1 {
            get {
                return ((double)(this["AngleBrace_Leg1"]));
            }
            set {
                this["AngleBrace_Leg1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public double AngleBrace_Leg2 {
            get {
                return ((double)(this["AngleBrace_Leg2"]));
            }
            set {
                this["AngleBrace_Leg2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.75")]
        public double AngleBrace_Gage {
            get {
                return ((double)(this["AngleBrace_Gage"]));
            }
            set {
                this["AngleBrace_Gage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.25")]
        public double AngleBrace_THK {
            get {
                return ((double)(this["AngleBrace_THK"]));
            }
            set {
                this["AngleBrace_THK"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.5625")]
        public double AngleBrace_K {
            get {
                return ((double)(this["AngleBrace_K"]));
            }
            set {
                this["AngleBrace_K"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2.125")]
        public double WT_Depth {
            get {
                return ((double)(this["WT_Depth"]));
            }
            set {
                this["WT_Depth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.25")]
        public double WT_StemTHK {
            get {
                return ((double)(this["WT_StemTHK"]));
            }
            set {
                this["WT_StemTHK"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public double WT_FlangeWidth {
            get {
                return ((double)(this["WT_FlangeWidth"]));
            }
            set {
                this["WT_FlangeWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.375")]
        public double WT_FlangeTHK {
            get {
                return ((double)(this["WT_FlangeTHK"]));
            }
            set {
                this["WT_FlangeTHK"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.6875")]
        public double WT_K {
            get {
                return ((double)(this["WT_K"]));
            }
            set {
                this["WT_K"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.4375")]
        public double WT_K1 {
            get {
                return ((double)(this["WT_K1"]));
            }
            set {
                this["WT_K1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2.25")]
        public double WT_FlangeGage {
            get {
                return ((double)(this["WT_FlangeGage"]));
            }
            set {
                this["WT_FlangeGage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("36")]
        public double MachineryMount_Width {
            get {
                return ((double)(this["MachineryMount_Width"]));
            }
            set {
                this["MachineryMount_Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double ShippingBeam_Height {
            get {
                return ((double)(this["ShippingBeam_Height"]));
            }
            set {
                this["ShippingBeam_Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.5")]
        public double BasePlate_THK {
            get {
                return ((double)(this["BasePlate_THK"]));
            }
            set {
                this["BasePlate_THK"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public double Clip_Height {
            get {
                return ((double)(this["Clip_Height"]));
            }
            set {
                this["Clip_Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double FloorSplice_LengthOverride {
            get {
                return ((double)(this["FloorSplice_LengthOverride"]));
            }
            set {
                this["FloorSplice_LengthOverride"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int EndStiffenerCount {
            get {
                return ((int)(this["EndStiffenerCount"]));
            }
            set {
                this["EndStiffenerCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int DividerStiffenerCount {
            get {
                return ((int)(this["DividerStiffenerCount"]));
            }
            set {
                this["DividerStiffenerCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public double Bundle_Width {
            get {
                return ((double)(this["Bundle_Width"]));
            }
            set {
                this["Bundle_Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.1344")]
        public double SideFrame_THK {
            get {
                return ((double)(this["SideFrame_THK"]));
            }
            set {
                this["SideFrame_THK"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("24")]
        public double SideFrame_Depth {
            get {
                return ((double)(this["SideFrame_Depth"]));
            }
            set {
                this["SideFrame_Depth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsBeltDrive {
            get {
                return ((bool)(this["IsBeltDrive"]));
            }
            set {
                this["IsBeltDrive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsGearDrive {
            get {
                return ((bool)(this["IsGearDrive"]));
            }
            set {
                this["IsGearDrive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsDirectDrive {
            get {
                return ((bool)(this["IsDirectDrive"]));
            }
            set {
                this["IsDirectDrive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsForced {
            get {
                return ((bool)(this["IsForced"]));
            }
            set {
                this["IsForced"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsInduced {
            get {
                return ((bool)(this["IsInduced"]));
            }
            set {
                this["IsInduced"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsMotorShaftUp {
            get {
                return ((bool)(this["IsMotorShaftUp"]));
            }
            set {
                this["IsMotorShaftUp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsMotorShaftDown {
            get {
                return ((bool)(this["IsMotorShaftDown"]));
            }
            set {
                this["IsMotorShaftDown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("286")]
        public int MotorFrameSize {
            get {
                return ((int)(this["MotorFrameSize"]));
            }
            set {
                this["MotorFrameSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50000")]
        public int TotalUnitWeight {
            get {
                return ((int)(this["TotalUnitWeight"]));
            }
            set {
                this["TotalUnitWeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2.9375")]
        public double FanShaft_Diameter {
            get {
                return ((double)(this["FanShaft_Diameter"]));
            }
            set {
                this["FanShaft_Diameter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public double Motor_CenterToCenter {
            get {
                return ((double)(this["Motor_CenterToCenter"]));
            }
            set {
                this["Motor_CenterToCenter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Murphy VS-2-EX")]
        public string Vibration_Sensor {
            get {
                return ((string)(this["Vibration_Sensor"]));
            }
            set {
                this["Vibration_Sensor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("180")]
        public double MachineryMount_Length {
            get {
                return ((double)(this["MachineryMount_Length"]));
            }
            set {
                this["MachineryMount_Length"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double MotorShift {
            get {
                return ((double)(this["MotorShift"]));
            }
            set {
                this["MotorShift"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double BoxWidth61 {
            get {
                return ((double)(this["BoxWidth61"]));
            }
            set {
                this["BoxWidth61"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double BoxWidth62 {
            get {
                return ((double)(this["BoxWidth62"]));
            }
            set {
                this["BoxWidth62"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double BoxWidth63 {
            get {
                return ((double)(this["BoxWidth63"]));
            }
            set {
                this["BoxWidth63"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double BoxWidth64 {
            get {
                return ((double)(this["BoxWidth64"]));
            }
            set {
                this["BoxWidth64"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double BoxWidth65 {
            get {
                return ((double)(this["BoxWidth65"]));
            }
            set {
                this["BoxWidth65"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double BoxWidth66 {
            get {
                return ((double)(this["BoxWidth66"]));
            }
            set {
                this["BoxWidth66"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double TubesheetTHK_61 {
            get {
                return ((double)(this["TubesheetTHK_61"]));
            }
            set {
                this["TubesheetTHK_61"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double TubesheetTHK_62 {
            get {
                return ((double)(this["TubesheetTHK_62"]));
            }
            set {
                this["TubesheetTHK_62"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double TubesheetTHK_63 {
            get {
                return ((double)(this["TubesheetTHK_63"]));
            }
            set {
                this["TubesheetTHK_63"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double TubesheetTHK_64 {
            get {
                return ((double)(this["TubesheetTHK_64"]));
            }
            set {
                this["TubesheetTHK_64"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double TubesheetTHK_65 {
            get {
                return ((double)(this["TubesheetTHK_65"]));
            }
            set {
                this["TubesheetTHK_65"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double TubesheetTHK_66 {
            get {
                return ((double)(this["TubesheetTHK_66"]));
            }
            set {
                this["TubesheetTHK_66"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double PlugsheetTHK_61 {
            get {
                return ((double)(this["PlugsheetTHK_61"]));
            }
            set {
                this["PlugsheetTHK_61"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double PlugsheetTHK_62 {
            get {
                return ((double)(this["PlugsheetTHK_62"]));
            }
            set {
                this["PlugsheetTHK_62"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double PlugsheetTHK_63 {
            get {
                return ((double)(this["PlugsheetTHK_63"]));
            }
            set {
                this["PlugsheetTHK_63"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double PlugsheetTHK_64 {
            get {
                return ((double)(this["PlugsheetTHK_64"]));
            }
            set {
                this["PlugsheetTHK_64"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double PlugsheetTHK_65 {
            get {
                return ((double)(this["PlugsheetTHK_65"]));
            }
            set {
                this["PlugsheetTHK_65"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double PlugsheetTHK_66 {
            get {
                return ((double)(this["PlugsheetTHK_66"]));
            }
            set {
                this["PlugsheetTHK_66"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double TubeLength {
            get {
                return ((double)(this["TubeLength"]));
            }
            set {
                this["TubeLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double TubeStickThru {
            get {
                return ((double)(this["TubeStickThru"]));
            }
            set {
                this["TubeStickThru"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool HeadersOutsideFrames {
            get {
                return ((bool)(this["HeadersOutsideFrames"]));
            }
            set {
                this["HeadersOutsideFrames"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsRequired_61 {
            get {
                return ((bool)(this["IsRequired_61"]));
            }
            set {
                this["IsRequired_61"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsRequired_62 {
            get {
                return ((bool)(this["IsRequired_62"]));
            }
            set {
                this["IsRequired_62"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsRequired_63 {
            get {
                return ((bool)(this["IsRequired_63"]));
            }
            set {
                this["IsRequired_63"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsRequired_64 {
            get {
                return ((bool)(this["IsRequired_64"]));
            }
            set {
                this["IsRequired_64"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsRequired_65 {
            get {
                return ((bool)(this["IsRequired_65"]));
            }
            set {
                this["IsRequired_65"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsRequired_66 {
            get {
                return ((bool)(this["IsRequired_66"]));
            }
            set {
                this["IsRequired_66"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double VerticalSpan61 {
            get {
                return ((double)(this["VerticalSpan61"]));
            }
            set {
                this["VerticalSpan61"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double VerticalSpan62 {
            get {
                return ((double)(this["VerticalSpan62"]));
            }
            set {
                this["VerticalSpan62"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double VerticalSpan63 {
            get {
                return ((double)(this["VerticalSpan63"]));
            }
            set {
                this["VerticalSpan63"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double VerticalSpan64 {
            get {
                return ((double)(this["VerticalSpan64"]));
            }
            set {
                this["VerticalSpan64"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double VerticalSpan65 {
            get {
                return ((double)(this["VerticalSpan65"]));
            }
            set {
                this["VerticalSpan65"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double VerticalSpan66 {
            get {
                return ((double)(this["VerticalSpan66"]));
            }
            set {
                this["VerticalSpan66"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double BoxLength61 {
            get {
                return ((double)(this["BoxLength61"]));
            }
            set {
                this["BoxLength61"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double BoxLength62 {
            get {
                return ((double)(this["BoxLength62"]));
            }
            set {
                this["BoxLength62"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double BoxLength63 {
            get {
                return ((double)(this["BoxLength63"]));
            }
            set {
                this["BoxLength63"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double BoxLength64 {
            get {
                return ((double)(this["BoxLength64"]));
            }
            set {
                this["BoxLength64"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double BoxLength65 {
            get {
                return ((double)(this["BoxLength65"]));
            }
            set {
                this["BoxLength65"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double BoxLength66 {
            get {
                return ((double)(this["BoxLength66"]));
            }
            set {
                this["BoxLength66"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double TopBottomTHK_61 {
            get {
                return ((double)(this["TopBottomTHK_61"]));
            }
            set {
                this["TopBottomTHK_61"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double TopBottomTHK_62 {
            get {
                return ((double)(this["TopBottomTHK_62"]));
            }
            set {
                this["TopBottomTHK_62"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double TopBottomTHK_63 {
            get {
                return ((double)(this["TopBottomTHK_63"]));
            }
            set {
                this["TopBottomTHK_63"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double TopBottomTHK_64 {
            get {
                return ((double)(this["TopBottomTHK_64"]));
            }
            set {
                this["TopBottomTHK_64"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double TopBottomTHK_65 {
            get {
                return ((double)(this["TopBottomTHK_65"]));
            }
            set {
                this["TopBottomTHK_65"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double TopBottomTHK_66 {
            get {
                return ((double)(this["TopBottomTHK_66"]));
            }
            set {
                this["TopBottomTHK_66"] = value;
            }
        }
    }
}
