//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileTools.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.9.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Beams_AreRotated {
            get {
                return ((bool)(this["Beams_AreRotated"]));
            }
            set {
                this["Beams_AreRotated"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.5")]
        public double Clip_THK {
            get {
                return ((double)(this["Clip_THK"]));
            }
            set {
                this["Clip_THK"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.375")]
        public double EndPanel_THK {
            get {
                return ((double)(this["EndPanel_THK"]));
            }
            set {
                this["EndPanel_THK"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.375")]
        public double SidePanel_THK {
            get {
                return ((double)(this["SidePanel_THK"]));
            }
            set {
                this["SidePanel_THK"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("W8x31")]
        public string Beam_Size {
            get {
                return ((string)(this["Beam_Size"]));
            }
            set {
                this["Beam_Size"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Standard")]
        public string PlenumDesignSetting {
            get {
                return ((string)(this["PlenumDesignSetting"]));
            }
            set {
                this["PlenumDesignSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("240")]
        public double Plenum_Length {
            get {
                return ((double)(this["Plenum_Length"]));
            }
            set {
                this["Plenum_Length"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("108")]
        public double Plenum_Width {
            get {
                return ((double)(this["Plenum_Width"]));
            }
            set {
                this["Plenum_Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int Fan_Count {
            get {
                return ((int)(this["Fan_Count"]));
            }
            set {
                this["Fan_Count"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("36")]
        public double Plenum_Depth {
            get {
                return ((double)(this["Plenum_Depth"]));
            }
            set {
                this["Plenum_Depth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Mid_Columns {
            get {
                return ((bool)(this["Mid_Columns"]));
            }
            set {
                this["Mid_Columns"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public double Fan_Diameter_Feet {
            get {
                return ((double)(this["Fan_Diameter_Feet"]));
            }
            set {
                this["Fan_Diameter_Feet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("24")]
        public double FanRing_Depth {
            get {
                return ((double)(this["FanRing_Depth"]));
            }
            set {
                this["FanRing_Depth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Motor Shaft Down")]
        public string MotorShaft_Orientation {
            get {
                return ((string)(this["MotorShaft_Orientation"]));
            }
            set {
                this["MotorShaft_Orientation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("A572_50")]
        public string MaterialSpecSetting {
            get {
                return ((string)(this["MaterialSpecSetting"]));
            }
            set {
                this["MaterialSpecSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public double Beam_Depth {
            get {
                return ((double)(this["Beam_Depth"]));
            }
            set {
                this["Beam_Depth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.25")]
        public double Beam_WebTHK {
            get {
                return ((double)(this["Beam_WebTHK"]));
            }
            set {
                this["Beam_WebTHK"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public double Beam_FlangeWidth {
            get {
                return ((double)(this["Beam_FlangeWidth"]));
            }
            set {
                this["Beam_FlangeWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.25")]
        public double Beam_FlangeTHK {
            get {
                return ((double)(this["Beam_FlangeTHK"]));
            }
            set {
                this["Beam_FlangeTHK"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.625")]
        public double Beam_K {
            get {
                return ((double)(this["Beam_K"]));
            }
            set {
                this["Beam_K"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.375")]
        public double Beam_K1 {
            get {
                return ((double)(this["Beam_K1"]));
            }
            set {
                this["Beam_K1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3.5")]
        public double Beam_FlangeGage {
            get {
                return ((double)(this["Beam_FlangeGage"]));
            }
            set {
                this["Beam_FlangeGage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2.25")]
        public double Beam_WebGage {
            get {
                return ((double)(this["Beam_WebGage"]));
            }
            set {
                this["Beam_WebGage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MotorBeam_Required {
            get {
                return ((bool)(this["MotorBeam_Required"]));
            }
            set {
                this["MotorBeam_Required"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("M000")]
        public string Project {
            get {
                return ((string)(this["Project"]));
            }
            set {
                this["Project"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Customer")]
        public string Customer {
            get {
                return ((string)(this["Customer"]));
            }
            set {
                this["Customer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Client")]
        public string Client {
            get {
                return ((string)(this["Client"]));
            }
            set {
                this["Client"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Location")]
        public string PlantLocation {
            get {
                return ((string)(this["PlantLocation"]));
            }
            set {
                this["PlantLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Purchase Order")]
        public string PurchaseOrder {
            get {
                return ((string)(this["PurchaseOrder"]));
            }
            set {
                this["PurchaseOrder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Item Number")]
        public string ItemNumber {
            get {
                return ((string)(this["ItemNumber"]));
            }
            set {
                this["ItemNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Your Initials")]
        public string Initials {
            get {
                return ((string)(this["Initials"]));
            }
            set {
                this["Initials"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("A")]
        public char Bank {
            get {
                return ((char)(this["Bank"]));
            }
            set {
                this["Bank"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Johnson_ExtraLength {
            get {
                return ((double)(this["Johnson_ExtraLength"]));
            }
            set {
                this["Johnson_ExtraLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Toggle_CreateDrawing {
            get {
                return ((bool)(this["Toggle_CreateDrawing"]));
            }
            set {
                this["Toggle_CreateDrawing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Toggle_Save {
            get {
                return ((bool)(this["Toggle_Save"]));
            }
            set {
                this["Toggle_Save"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Toggle_DeleteFiles {
            get {
                return ((bool)(this["Toggle_DeleteFiles"]));
            }
            set {
                this["Toggle_DeleteFiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("120")]
        public double TotalColumnHeight {
            get {
                return ((double)(this["TotalColumnHeight"]));
            }
            set {
                this["TotalColumnHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public double BasePlate_Width {
            get {
                return ((double)(this["BasePlate_Width"]));
            }
            set {
                this["BasePlate_Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public double BasePlate_Length {
            get {
                return ((double)(this["BasePlate_Length"]));
            }
            set {
                this["BasePlate_Length"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4.5")]
        public double BasePlate_WidthHoleSpacing {
            get {
                return ((double)(this["BasePlate_WidthHoleSpacing"]));
            }
            set {
                this["BasePlate_WidthHoleSpacing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4.5")]
        public double BasePlate_LengthHoleSpacing {
            get {
                return ((double)(this["BasePlate_LengthHoleSpacing"]));
            }
            set {
                this["BasePlate_LengthHoleSpacing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.8125")]
        public double BasePlate_HoleDiameter {
            get {
                return ((double)(this["BasePlate_HoleDiameter"]));
            }
            set {
                this["BasePlate_HoleDiameter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("54")]
        public double MachineryMount_Height {
            get {
                return ((double)(this["MachineryMount_Height"]));
            }
            set {
                this["MachineryMount_Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TX")]
        public string BraceType {
            get {
                return ((string)(this["BraceType"]));
            }
            set {
                this["BraceType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.8125")]
        public double HoleDiameter_Structural {
            get {
                return ((double)(this["HoleDiameter_Structural"]));
            }
            set {
                this["HoleDiameter_Structural"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public double BraceAngle {
            get {
                return ((double)(this["BraceAngle"]));
            }
            set {
                this["BraceAngle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public double AngleBrace_Leg1 {
            get {
                return ((double)(this["AngleBrace_Leg1"]));
            }
            set {
                this["AngleBrace_Leg1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public double AngleBrace_Leg2 {
            get {
                return ((double)(this["AngleBrace_Leg2"]));
            }
            set {
                this["AngleBrace_Leg2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.75")]
        public double AngleBrace_Gage {
            get {
                return ((double)(this["AngleBrace_Gage"]));
            }
            set {
                this["AngleBrace_Gage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.25")]
        public double AngleBrace_THK {
            get {
                return ((double)(this["AngleBrace_THK"]));
            }
            set {
                this["AngleBrace_THK"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.5625")]
        public double AngleBrace_K {
            get {
                return ((double)(this["AngleBrace_K"]));
            }
            set {
                this["AngleBrace_K"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2.125")]
        public double WT_Depth {
            get {
                return ((double)(this["WT_Depth"]));
            }
            set {
                this["WT_Depth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.25")]
        public double WT_StemTHK {
            get {
                return ((double)(this["WT_StemTHK"]));
            }
            set {
                this["WT_StemTHK"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public double WT_FlangeWidth {
            get {
                return ((double)(this["WT_FlangeWidth"]));
            }
            set {
                this["WT_FlangeWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.375")]
        public double WT_FlangeTHK {
            get {
                return ((double)(this["WT_FlangeTHK"]));
            }
            set {
                this["WT_FlangeTHK"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.6875")]
        public double WT_K {
            get {
                return ((double)(this["WT_K"]));
            }
            set {
                this["WT_K"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.4375")]
        public double WT_K1 {
            get {
                return ((double)(this["WT_K1"]));
            }
            set {
                this["WT_K1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2.25")]
        public double WT_FlangeGage {
            get {
                return ((double)(this["WT_FlangeGage"]));
            }
            set {
                this["WT_FlangeGage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("36")]
        public double MachineryMount_Width {
            get {
                return ((double)(this["MachineryMount_Width"]));
            }
            set {
                this["MachineryMount_Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double ShippingBeam_Height {
            get {
                return ((double)(this["ShippingBeam_Height"]));
            }
            set {
                this["ShippingBeam_Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.5")]
        public double BasePlate_THK {
            get {
                return ((double)(this["BasePlate_THK"]));
            }
            set {
                this["BasePlate_THK"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public double Clip_Height {
            get {
                return ((double)(this["Clip_Height"]));
            }
            set {
                this["Clip_Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double FloorSplice_LengthOverride {
            get {
                return ((double)(this["FloorSplice_LengthOverride"]));
            }
            set {
                this["FloorSplice_LengthOverride"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int EndStiffenerCount {
            get {
                return ((int)(this["EndStiffenerCount"]));
            }
            set {
                this["EndStiffenerCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int DividerStiffenerCount {
            get {
                return ((int)(this["DividerStiffenerCount"]));
            }
            set {
                this["DividerStiffenerCount"] = value;
            }
        }
    }
}
